### ISSUE TITLE
Compiledoutput.drive is not a function

### ISSUE THREAD

**Issue by lpi** [nuprl/augur#26]
I'm getting this issue when trying to apply augur to a demo-app, which is a naked expressJs app.

TypeError: compiledOutput.drive is not a function
    at executeInstructionsFromFile (/home/lpi/augur/ts/dist/src/utils.js:195:20)
    at exports.run (/home/lpi/augur/ts/runner/run.js:225:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Tried using the default spec.json, but it doesn't seem to do anything. Does this happen when I'm using a native function or something along those lines?

**Comment by lpi** [comment]
That doesn't seem to be the case: and the function in analysis.output seems to be a function.

**Comment by mwaldrich** [comment]
Typically, you see that error in Augur when the program you're analyzing crashed; Augur is saying it has nothing left to analyze for taint flows. Augur doesn't crash if your code is using unsupported native functions.

Could you link me the code/repo you're trying to analyze? I can take a look and see what's going on.

**Comment by lpi** [comment]
Sure! Here's my test app which displays this. It's a pretty naked express app.

https://github.com/lpi/simple-taint-demo

Thank you!

**Comment by lpi** [comment]
Some other issues: I dropped express, and made a web server manually, this fails, albiet in a different way:

`const http = require('http');

const hostname = '127.0.0.1';
const port = 3000;

const server = http.createServer((req, res) => {
  res.statusCode = 200;
  var x = getPassword();
  log(x);
  res.setHeader('Content-Type', 'text/plain');
  res.end('Hello World');
});

server.listen(port, hostname, () => {
  console.log(`Server running at http://${hostname}:${port}/`);
});

function getPassword() {
  return "123456";
}

function log (message) {
  console.log(message);
}`

When I run this, augur gets stuck at 'Instrumenting code
  =>  /home/lpi/demos/simple-taint-demo/index.js...
(    ● )^C
'
forever

**Comment by lpi** [comment]
I'm running nodeprof via docker, the test cases work for me. Changing my code to to


```
var x = getPassword();
log(x);I'm running nodeprof via docker, the test cases work for me. Changing my code to to


var x = getPassword();
log(x);


function getPassword() {
  return "123456";
}

function log (message) {
  console.log(message);
}


function getPassword() {
  return "123456";
}

function log (message) {
  console.log(message);
}
```

works as expected.
