### ISSUE TITLE
Failed on docker

### ISSUE THREAD

**Issue by dreamking60** [nuprl/augur#8]
I install the docker based on the https://docs.docker.com/engine/install/ubuntu/#install-using-the-convenience-script
However, after this, I find I can't successfully init the nodeprof for it return copy wrong.

> Step 8/10 : COPY ${nodeprof_repo} /root/nodeprof
COPY failed: file not found in build context or excluded by .dockerignore: stat nodeprof-clones/vanilla/nodeprof.js: file does not exist

**Comment by mwaldrich** [comment]
Ah that's unfortunate! Just yesterday we changed how things work with Docker, and it looks like it broke things. I'll fix that in a bit and let you know when it's working

**Comment by mwaldrich** [comment]
Things should be good now. Please try deleting your installation and starting from scratch, as the build instructions have changed.

You shouldn't encounter any issues getting the Docker image anymore, as you no longer have to build it locally on your machine. Instead, the image now gets fetched from Dockerhub.

Let me know if this fixes it!

**Comment by dreamking60** [comment]
> Things should be good now. Please try deleting your installation and starting from scratch, as the build instructions have changed.
> 
> You shouldn't encounter any issues getting the Docker image anymore, as you no longer have to build it locally on your machine. Instead, the image now gets fetched from Dockerhub.
> 
> Let me know if this fixes it!

Well, It works well. Thanks your help.
